version: '3.3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../app:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wotmapstatistics
      MYSQL_USER: root
      MYSQL_PASSWORD: stat1sticaSupr3me
      MYSQL_ROOT_PASSWORD: stat1sticaSupr3me
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ../app:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - laravel
